application: lexigraph
version: 1
runtime: python
api_version: 1

handlers:
    - url: /(css|js|images|files)/(.+)
      static_files: static/\1/\2
      upload: static/(css|js|images|files)/(.+)
   
    - url: /cron/.*
      script: main.py
      login: admin
    
    - url: /.*
      script: main.py
