application: lexigraph
version: 1
runtime: python
api_version: 1

handlers:
    - url: /(css|images|files)/(.+)
      static_files: static/\1/\2
      upload: static/(css|images|files)/(.+)

    - url: /js/(.+)
      static_files: js/\1
      upload: static/js/(.+)
   
    - url: /cron/.*
      script: main.py
      login: admin
    
    - url: /.*
      script: main.py
