application: lexigraph
version: 1
runtime: python
api_version: 1

handlers:
    - url: /(css|images|files)/(.+)
      static_files: static/\1/\2
      upload: static/(css|images|files)/(.+)

    - url: /js/(.+)\.js
      static_files: js/\1.js
      upload: js/(.+)\.js

    - url: /versioned_js/(.+)/(.+)\.js
      static_files: js/\2.js
      upload: js/(.+)\.js
      expiration: 10d
   
    - url: /cron/.*
      script: main.py
      login: admin
    
    - url: /.*
      script: main.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?SConstruct$
- .git/
- js/closure
- js/closure-templates
- vendor/closure
- vendor/closure-templates
- bin/
- ^(.*/)?\.map$
